name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history is needed for SonarCloud analysis

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run SonarCloud Scanner
        working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=my-secure-app \
            -Dsonar.organization=Shubh0808 \
            -Dsonar.sources=. \
            -Dsonar.exclusions=node_modules/**,tests/** \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.language=js \
            -Dsonar.sourceEncoding=UTF-8

  snykScan:
    runs-on: ubuntu-latest
    needs: sonarCloudScan
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Snyk Test in backend folder
        run: |
          cd backend
          npm install -g snyk
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  trivyScan:
    runs-on: ubuntu-latest
    needs: snykScan
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build -t myapp-backend:latest ./backend

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.15.0
        with:
          image-ref: myapp-backend:latest
