- uses: actions/checkout@v3
  with:
    fetch-depth: 0  # ensures full Git history

- name: Install Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '18'

- name: Install backend dependencies
  run: npm ci
  working-directory: ./backend

- name: Run SonarQube Scanner from root
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  run: |
    npm install -g sonar-scanner
    sonar-scanner \
      -Dsonar.projectKey=my-secure-app \
      -Dsonar.sources=./backend \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.login=$SONAR_TOKEN
