name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarQubeScan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for full git history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm ci

      - name: Debug Git
        run: |
          git status
          git log -1

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=my-secure-app \
            -Dsonar.sources=backend \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

  snykScan:
    runs-on: ubuntu-latest
    needs: sonarQubeScan

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Snyk Test in backend folder
        run: |
          cd backend
          npm ci
          npm install -g snyk
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  trivyScan:
    runs-on: ubuntu-latest
    needs: snykScan

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build -t myapp-backend:latest ./backend

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.15.0
        with:
          image-ref: myapp-backend  # ✅ fix typo here (was "myapp-backe")
